plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wp7.navbar'
    compileSdk 36
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId "com.wp7.navbar"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // LSPosed API (compileOnly: 不在APK内打包，由框架提供)
    compileOnly 'de.robv.android.xposed:api:82'
    // 可选：XposedBridge 运行时支持
    compileOnly 'de.robv.android.xposed:api:82:sources'
}
